spring:
  application:
    name: eureka-client
  server:
    port: 6001
#  profiles:
#      active: client1
  # mysql 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/,http://localhost:5003/eureka/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #对应你的mapper.xml映射文件
  type-aliases-package: com.qsn.eurekaclient.entity #对应实体类
