server:
  port: 12701

spring:
  application:
    #指定eureka主机名称
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    #当前主机是否需要注册到eureka注册服务中心。 默认为 true。设为 false，仅作为服务中心，不作为服务客户端。
    register-with-eureka: false
    #当前主机是否需要获取注册信息。 默认为true。设为false，不从服务中心检索注册的服务。
    fetch-registry: false
    #服务中心地址
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://localhost:12700/eureka/,http://localhost:9500/eureka/,http://localhost:9600/eureka/
  server:
    eviction-interval-timer-in-ms: 5000 #清理间隔（单位毫秒，默认是60*1000）
    enable-self-preservation: true # 默认为true，设为false，关闭自我保护
    # Eureka Server 在运行期间会去统计心跳失败比例在 15 分钟之内是否低于 85%
    renewal-percent-threshold: 0.49 # 默认是0.85，本地单机测试设为0.49
